name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name:  Deploy resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscritionId: f801f268-4bbc-4ba4-8ee5-c6447296eaef
          region: West Europe
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions   
      
      - name: List resource Groups for validation
        uses: Azure/cli@v1.0.7
        with:
          inlinescript: |
            az group list --subscription f801f268-4bbc-4ba4-8ee5-c6447296eaef





